/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type DiamondArgsStruct = {
  owner: PromiseOrValue<string>;
  init: PromiseOrValue<string>;
  initCalldata: PromiseOrValue<BytesLike>;
};

export type DiamondArgsStructOutput = [string, string, string] & {
  owner: string;
  init: string;
  initCalldata: string;
};

export declare namespace IDiamond {
  export type FacetCutStruct = {
    facetAddress: PromiseOrValue<string>;
    action: PromiseOrValue<BigNumberish>;
    functionSelectors: PromiseOrValue<BytesLike>[];
  };

  export type FacetCutStructOutput = [string, number, string[]] & {
    facetAddress: string;
    action: number;
    functionSelectors: string[];
  };
}

export interface DiamondFactoryInterface extends utils.Interface {
  functions: {
    "deployDiamond((address,uint8,bytes4[])[],(address,address,bytes))": FunctionFragment;
    "initDeployFacet()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deployDiamond" | "initDeployFacet"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployDiamond",
    values: [IDiamond.FacetCutStruct[], DiamondArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "initDeployFacet",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployDiamond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initDeployFacet",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DiamondFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DiamondFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployDiamond(
      _diamondCut: IDiamond.FacetCutStruct[],
      _args: DiamondArgsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initDeployFacet(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deployDiamond(
    _diamondCut: IDiamond.FacetCutStruct[],
    _args: DiamondArgsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initDeployFacet(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployDiamond(
      _diamondCut: IDiamond.FacetCutStruct[],
      _args: DiamondArgsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    initDeployFacet(
      overrides?: CallOverrides
    ): Promise<[string, string, string, string]>;
  };

  filters: {};

  estimateGas: {
    deployDiamond(
      _diamondCut: IDiamond.FacetCutStruct[],
      _args: DiamondArgsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initDeployFacet(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployDiamond(
      _diamondCut: IDiamond.FacetCutStruct[],
      _args: DiamondArgsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initDeployFacet(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
