/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISBT, ISBTInterface } from "../../interfaces/ISBT";

const _abi = [
  {
    inputs: [],
    name: "SoulBound",
    type: "error",
  },
] as const;

export class ISBT__factory {
  static readonly abi = _abi;
  static createInterface(): ISBTInterface {
    return new utils.Interface(_abi) as ISBTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISBT {
    return new Contract(address, _abi, signerOrProvider) as ISBT;
  }
}
