/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISignatureRecovery,
  ISignatureRecoveryInterface,
} from "../../interfaces/ISignatureRecovery";

const _abi = [
  {
    inputs: [],
    name: "Forbidden",
    type: "error",
  },
] as const;

export class ISignatureRecovery__factory {
  static readonly abi = _abi;
  static createInterface(): ISignatureRecoveryInterface {
    return new utils.Interface(_abi) as ISignatureRecoveryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISignatureRecovery {
    return new Contract(address, _abi, signerOrProvider) as ISignatureRecovery;
  }
}
